makim-org/makim

makim/__main__.py, makim/makim.py
This PR aims to suppress the error message from sh traceback.
* ```...```
This PR is a:
About this PR:
```
```
=> fix: Suppress the sh traceback message error

.github/workflows/main.yaml
This PR aims to add support for MacOS on CI.
It was added an initial support for windows on CI, but the full implementation will be done later, because currently there is a problem with poetry on windows.
* ```...```
This PR is a:
About this PR:
```
```
=> ci: Add support for MacOS

.github/workflows/release.yaml, .makim.yaml
Fix release workflow
* ```...```
This PR is a:
About this PR:
```
```
=> fix: Fix release workflow

.github/workflows/main.yaml, makim/makim.py, tests/.makim-bash-group-scope.yaml, tests/.makim-bash-main-scope.yaml, tests/.makim-bash-target-scope.yaml
This PR aims to add support for user defined shell app
PS: for now it considers that all the shell apps would use `-c` as a flag for receiving a command line as a string
resolve #17 
* ```...```
This PR is a:
About this PR:
```
```
=> feat: Add support for user defined shell app

.makim.yaml, makim/__main__.py, makim/makim.py, tests/.makim-unittest.yaml, tests/test_makim.py
This PR aims to fix the if statement and the arguments used both by dependencies
* ```...```
This PR is a:
About this PR:
```
```
=> fix: Fix IF statement and arguments used by dependencies

.github/workflows/main.yaml, .makim.yaml, makim/makim.py, tests/.makim-unittest.yaml, tests/test_makim.py
Currently, the conditional parameter is not honored when the --verbose flag is not given
* ```...```
This PR is a:
About this PR:
```
```
=> fix: Fix conditional parameter when --verbose is not given

.makim.yaml, makim/__main__.py, makim/makim.py, tests/.makim-bash-group-scope.yaml, tests/.makim-bash-main-scope.yaml, tests/.makim-bash-target-scope.yaml, tests/.makim-complex.yaml, tests/.makim-simple.yaml, tests/.makim-unittest.yaml
fix #20 
This PR is a:
About this PR:
Now running only `makim` or `makim --verbose` will list the help
```
```
=> fix(groups): change groups to accept dict instead of list && improve help cmd

pyproject.toml
If publish it should show more information and use the readme if I get that correct.
=> readme, homepage url added in pyproject.toml

.github/workflows/main.yaml
=> chore(ci): checks the PR title according to semantic rel(#31)

makim/makim.py, poetry.lock, pyproject.toml, tests/.makim-complex.yaml, tests/.makim-unittest.yaml, tests/test_failure.py
* ```...```
This PR is a:
About this PR:
```
```
=> fix: Break bash target when any line fails

.makim.yaml, conda/dev.yaml, pyproject.toml
This PR proposes to fix the release workflow and fix broken dependencies 
ref: https://github.com/ionrock/cachecontrol/issues/292#issuecomment-1536120527
* ```...```
This PR is a:
About this PR:
```
```
=> fix: Fix release workflow and broken dependencies

.github/workflows/main.yaml, .github/workflows/release.yaml, .makim.yaml, README.md, conda/dev.yaml, docs/template.md, makim/makim.py, tests/.makim-complex.yaml, tests/.makim-env.yaml
This PR fixes the issues about the rendering flow of `env`, `vars`, and `args`, considering the three different scope: `global`, `group`, and `target`. Details where added to the documentation.
Additionally, it fixes the documentation workflow. 
* ```...```
This PR is a:
About this PR:
```
```
=> fix: Fix the rendering flow of env, vars and args

.makim.yaml, .pre-commit-config.yaml, makim/__main__.py, makim/cli.py, makim/errors.py, makim/makim.py, pyproject.toml, tests/.containers-sugar.yaml, tests/.makim-bash-group-scope.yaml, tests/.makim-bash-main-scope.yaml, tests/.makim-bash-target-scope.yaml, tests/.makim-complex.yaml, tests/.makim-env.yaml, tests/.makim-simple.yaml, tests/.makim-unittest.yaml
* ```...```
This PR is a:
About this PR:
```
```
=> refactor(linter): Improve linter configuration and add more tools

.github/workflows/release.yaml, .makim.yaml, .pre-commit-config.yaml, .releaserc.json, conda/dev.yaml, conda/release.yaml, makim/cli.py, makim/makim.py, pyproject.toml, tests/test_failure.py, tests/test_success.py
* ```...```
This PR is a:
About this PR:
```
```
=> chore(autoformat): Move from blue to ruff

README.md
=> docs: add small section about xonsh and fix old style documentation

.github/workflows/main.yaml
* ```...```
This PR is a:
About this PR:
```
```
=> chore(ci): Fix /tmp for macos

.makim.yaml, .releaserc.json
* ```...```
This PR is a:
About this PR:
```
```
=> chore(release): Fix the release workflow

docs/features.md
* ```...```
This PR is a:
About this PR:
```
```
=> docs: Improve Features documentation structure

.github/workflows/main.yaml
* ```...```
This PR is a:
About this PR:
```
```
=> ci: Fix ON attribute in CI workflow main.yaml

pyproject.toml
* ```...```
This PR is a:
About this PR:
```
```
=> chore: Add configuration to fix issues automatically with ruff

pyproject.toml, src/makim/cli.py
=> feat: suggest probable command

.github/workflows/main.yaml, .makim.yaml, src/makim/core.py, tests/smoke/.makim-vars.yaml
* ```...```
This PR is a:
About this PR:
```
```
=> feat: Allow vars with complex types (list, dict)

.prettierignore, .prettierrc.yaml, docs/contributing.md
* ```...```
This PR is a:
About this PR:
```
```
=> docs: Update the contributing guide

.github/workflows/docs.yaml, .github/workflows/main.yaml
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> fix: Fix issues with python version on CI

.github/workflows/main.yaml, pyproject.toml
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> chore(ci): Fix linter job on CI

.github/workflows/docs.yaml, .github/workflows/main.yaml, poetry.lock, pyproject.toml
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> fix: Fix xonsh version

.makim.yaml, containers/Dockerfile
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> chore: Add initial infrastructure for ssh tests

.makim.yaml
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> chore: fix commands for docker

README.md
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> docs: Fix badges

docs/features.md, docs/spec.md, mkdocs.yaml
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> docs: Fix features and spec pages

README.md
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> docs: Add link to an example on google colab

.releaserc.json, docs/installation.md
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> chore(release): Fix executable name and improve documentation

.makim.yaml, README.md, tests/smoke/.makim-scheduler.yaml
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> tests: Improve tests with problems with scheduler and hooks

src/makim/core.py
1. **Serialization Fix for Deepcopy & Pickling**  
- add `__getstate__` method to ensure that the `Makim` instance can be safely deep copied and serialized without errors  
2. **Group Name Resolution Fix**
- add fallback logic in `_change_group_data()` to automatically set the group to the only available group when the current group name is not found
Solving issue #148 
```sh
makim smoke-tests.scheduler 
```
This PR is a:
About this PR:
complexity.
Please look into the issue #148 discussion for my discovery and approach please
```
```
=> fix(test): schedulers cannot be serialized resulting to scheduler test failure

.github/workflows/main.yaml, tests/smoke/.makim-dir-absolute-path.yaml, tests/smoke/.makim-dir-no-path.yaml, tests/smoke/.makim-dir-relative-path.yaml
This PR aims to fix test cases failing on mac due to /tmp sysmlink ,it fixes the following tests
- dir-relative-path
- dir-no-path
- dir-absolute-path
Resolves #153 
```sh
makim smoke-tests.dir-relative-path
makim smoke-tests.dir-no-path
makim smoke-tests.dir-absolute-path
```
This PR is a:
About this PR:
complexity.
```
```
=> tests: Fix multiple test failure due to /tmp symlink on macOS

.makim.yaml, pyproject.toml, src/makim/cli/__init__.py, src/makim/cli/config.py, src/makim/core.py, tests/smoke/.makim-hooks.yaml
This PR aims to implement support for skipping hooks while execution, It also includes
test cases for testing skip-hook functionality
Resolves #130 
```sh
makim --skip-hooks group.task
```
or
```sh
makim smoke-tests.run-hooks
```
This PR is a:
About this PR:
complexity.
I have disabled the PLR0913 rule for main function in cli/__init__.py since I added 
new argument for skipping hooks please do let me know if it works or I will
refactor and improve it
```
```
=> feat: Implement --skip-hooks flag to bypass hook execution

README.md, docs/features.md
This PR aims to update documentation for the new CLI flag feature
`--skip-hooks` #159
resolves #161 
```sh
mkdocs serve
```
This PR is a:
About this PR:
complexity.
```
```
=> docs: update hooks documentation to include info about  --skip-hooks flag

.github/workflows/main.yaml, .gitignore, .makim.yaml, src/makim/core.py, src/makim/schema.json, src/makim/task_logging.py, tests/smoke/.makim-file-log.yaml
This PR aims to implement logging for tasks and also provides options to format logs
and specify level for the log (err,out,both)
resolves #38 
```yaml
groups:
mygroup:
tasks:
tasks:
log:
path: /tmp/log.txt
level: err
format: "%(asctime)s - %(file)s - %(levelname)s - %(task)s - %(message)s"
```
or
```sh
makim smoke-tests.task-logger
```
This PR is a:
About this PR:
complexity.
```
```
=> feat: Add an option for tasks to specify a log file, log format and log level

README.md, docs/features.md, docs/spec.md
This PR updates the specification page and features page to document the file logging feature
resolves #176 
```sh
mkdocs serve
```
This PR is a:
About this PR:
complexity.
```
```
=> docs(spec): update documentation to include info about log config

.github/workflows/main.yaml, .makim.yaml, README.md, docs/features.md, docs/spec.md, src/makim/core.py, tests/smoke/.makim-retry.yaml
This PR aims to add smoke tests and update the documentation specs for retry mechanism for tasks, Update on issue #174 
```sh
makim smoke-tests.retry
```
```sh
mkdocs serve
```
This PR is a:
About this PR:
complexity.
```
```
=> test(retry): Add smoke tests and update documentation for retry mechanism for tasks

src/makim/scheduler.py
Enhances the Makim scheduler's reliability and maintainability by improving error handling, logging, safety measures, and configuration synchronization. 
Solve #180
=> Improve error handling and logging in task scheduler module

.github/workflows/main.yaml, .makim.yaml, src/makim/core.py, src/makim/schema.json, tests/smoke/.makim-hooks.yaml, tests/smoke/.makim-task-conditionals.yaml
This PR aims to add feature to validate execution of tasks based on conditionals and add corresponding tests,
It also adds context for `vars` in conditionals for hooks and corresponding tests
resolves #182 
```sh
makim smoke-tests.validate-conditionals
```
```sh
makim smoke-tests.run-hooks
```
This PR is a:
About this PR:
complexity.
```
```
=> feat(core): Add conditionals to validate execution of tasks

.github/workflows/main.yaml, conda/dev-win.yaml, conda/dev.yaml, docs/features.md, docs/spec.md, docs/template.md, mkdocs.yaml, poetry.lock, pyproject.toml, src/makim/core.py
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> feat: Replace sh by xh

.github/workflows/release.yaml
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> fix(CI): Fix the CI trigger for tags

.github/workflows/release.yaml
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> fix: Fix sync between semantic release and packages release

.github/workflows/main.yaml, poetry.lock, pyproject.toml, src/makim/core.py, tests/smoke/.makim-sugar.yaml, tests/smoke/.sugar.yaml
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> chore: Fix sugar tests and dependences for development

.github/workflows/lsp.yaml
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> chore(ci): Fix the LSP CI job

src/makim/schema.json
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> chore: change title of schema

.github/workflows/lsp.yaml
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> chore(lsp): Force git token for LSP workflow

.github/workflows/stale.yaml
- `...`
This PR is a:
About this PR:
complexity.
```
```
=> chore(ci): Increase timelines for stale workflow
